#!/usr/bin/env python3
from pathlib import Path
import sys

ROOT = Path(sys.argv[1]).resolve()
PATH = ROOT / "services/local-core/src/book_os_core/auto_book_exports.py"
text = PATH.read_text(encoding="utf-8")
old = '''        document_html = "\\n".join(\n            item.get_content().decode("utf-8", errors="replace")\n            for item in reopened.get_items_of_type(ebooklib.ITEM_DOCUMENT)\n        )\n        expected_alt_texts = [\n            visual.alt_text for chapter in master.chapters for visual in chapter.visuals\n        ]\n        expected_image_names = [\n            f"images/{visual.object_id}.png"\n            for chapter in master.chapters\n            for visual in chapter.visuals\n        ]\n        references_ok = all(value in document_html for value in expected_alt_texts + expected_image_names)\n        semantic_fragments = [\n            fragment\n            for chapter in master.chapters\n            for paragraph in chapter.paragraphs\n            for fragment in self._semantic_fragments(paragraph)\n        ]\n        semantic_content_ok = all(escape(value) in document_html or value in document_html for value in semantic_fragments)\n'''
new = '''        document_items = list(reopened.get_items_of_type(ebooklib.ITEM_DOCUMENT))\n        document_html = "\\n".join(\n            item.get_content().decode("utf-8", errors="replace") for item in document_items\n        )\n        expected_alt_texts = [\n            visual.alt_text for chapter in master.chapters for visual in chapter.visuals\n        ]\n        expected_image_names = [\n            f"images/{visual.object_id}.png"\n            for chapter in master.chapters\n            for visual in chapter.visuals\n        ]\n        references_ok = all(value in document_html for value in expected_alt_texts + expected_image_names)\n        semantic_fragments = [\n            fragment\n            for chapter in master.chapters\n            for paragraph in chapter.paragraphs\n            for fragment in self._semantic_fragments(paragraph)\n        ]\n        semantic_text_parts: list[str] = []\n        for item in document_items:\n            try:\n                root = ET.fromstring(item.get_content())\n            except ET.ParseError as exc:\n                raise AutoBookExportError("EPUB semantic QA could not parse a document") from exc\n            semantic_text_parts.extend(root.itertext())\n        semantic_plain_text = " ".join(" ".join(semantic_text_parts).split())\n        semantic_content_ok = all(\n            " ".join(value.split()) in semantic_plain_text for value in semantic_fragments\n        )\n'''
if text.count(old) != 1:
    raise SystemExit(f"expected one T07b EPUB semantic QA block, found {text.count(old)}")
PATH.write_text(text.replace(old, new, 1), encoding="utf-8")
print("T07b EPUB plaintext semantic QA correction applied")
