import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, test, vi } from "vitest";
afterEach(cleanup);
import { BookBenchPanel } from "./BookBenchPanel";
import { coreApi } from "./api";
vi.mock("./api",()=>({coreApi:vi.fn()}));
const project={book_id:"B",working_title:"Book",chapters:[]} as never;
test("run shows dimension evidence and explicit editorial handoff",async()=>{vi.mocked(coreApi).mockResolvedValueOnce({snapshot_id:"S"}).mockResolvedValueOnce([]).mockResolvedValueOnce({snapshot_id:"S",snapshot_hash:"abcdef123456789",current:true,blocking_dimensions:[],dimensions:[{dimension:"AI_PROSE_PATHOLOGY",state:"ATTENTION",run_ids:["R"],metrics:{},findings:[{finding_id:"F",dimension:"AI_PROSE_PATHOLOGY",category:"FALSE_CONTRAST",location:"revision:x sentence:1",evidence:{pattern:"не X, а Y"},severity:"ATTENTION",confidence:.9,recommended_action:"Human review"}]}]}).mockResolvedValueOnce({finding_id:"E"});render(<BookBenchPanel project={project}/>);fireEvent.click(screen.getByText("Build exact snapshot"));await screen.findByText("Exact snapshot ready");fireEvent.click(screen.getByText("Run deterministic"));await screen.findByText("FALSE_CONTRAST");fireEvent.click(screen.getByText("Send to Editorial Inbox"));await screen.findByText(/Sent to Editorial Inbox/);});
test("scorecards remain per-dimension with no overall score",async()=>{vi.mocked(coreApi).mockResolvedValueOnce({dataset_snapshot_id:"D"}).mockResolvedValueOnce([{scorecard_id:"S",config_id:"fake-a",role:"WRITER",dimensions:{AUTHOR_VOICE:{pass:1}},severe_failure_count:0,pass_count:1,attention_count:0,blocking_count:0,latency_ms:1,cost_usd:0,usage:{external_calls:0}}]);render(<BookBenchPanel project={project}/>);fireEvent.click(screen.getByText("Compare fake configs"));await waitFor(()=>expect(screen.getByLabelText("Configuration scorecards")).toBeInTheDocument());expect(screen.getAllByText(/no overall score/i).length).toBeGreaterThan(0);});
