const LABELS: Record<string, string> = {
  ALL: "Все",
  DRAFT: "Черновик",
  PROPOSED: "Предложено",
  REVIEWED: "Проверено",
  APPROVED: "Утверждено",
  LOCKED: "Зафиксировано",
  SUPERSEDED: "Заменено",
  OPEN: "Открыто",
  RESOLVED: "Закрыто",
  WAIVED: "Допущено человеком",
  CURRENT: "Текущая версия",
  HISTORY: "История",
  STALE: "Устарело",
  ACTIVE: "Активен",
  COMPLETED: "Завершён",
  ABORTED: "Остановлен",
  PASS: "Пройдено",
  ATTENTION: "Требует внимания",
  BLOCKING: "Блокирует",
  INFO: "Информация",
  MINOR: "Незначительная",
  MAJOR: "Существенная",
  CRITICAL: "Критическая",
  UNREVIEWED: "Не проверено",
  SUPPORTED: "Подтверждено",
  PARTIALLY_SUPPORTED: "Подтверждено частично",
  DISPUTED: "Оспаривается",
  UNSUPPORTED: "Не подтверждено",
  REJECTED: "Отклонено",
  SUPPORTS: "Подтверждает",
  PARTIALLY_SUPPORTS: "Подтверждает частично",
  CONTRADICTS: "Противоречит",
  CONTEXT_ONLY: "Только контекст",
  METADATA_ONLY: "Только метаданные",
  ABSTRACT_AVAILABLE: "Доступен аннотационный материал",
  FULL_SOURCE_INSPECTED: "Источник изучен",
  PRIMARY: "Первичный источник",
  SECONDARY: "Вторичный источник",
  UNCLASSIFIED: "Не классифицирован",
  QUANTITATIVE: "Количественное",
  EMPIRICAL: "Эмпирическое",
  CAUSAL: "Причинное",
  HISTORICAL: "Историческое",
  ATTRIBUTION: "Атрибуция",
  CASE_ASSERTION: "Утверждение из кейса",
  LEGAL_REGULATORY: "Правовое / нормативное",
  CONSENSUS: "Консенсус",
  INTERPRETIVE: "Интерпретация",
  AUTHORIAL: "Авторское",
  LEXICAL: "Лексический",
  SEMANTIC: "Семантический",
  HYBRID: "Гибридный",
  LEXICAL_READY: "Лексический индекс готов",
  SEMANTIC_READY: "Семантический индекс готов",
  MANUSCRIPT_UNIT: "Фрагмент рукописи",
  BOOK_CONTRACT: "Контракт книги",
  CHAPTER_CONTRACT: "Контракт главы",
  CLAIM: "Утверждение",
  DEVELOPMENTAL_EDITOR: "Структурный редактор",
  CROSS_BOOK_AUDITOR: "Редактор целой книги",
  FACT_CHECKER: "Фактчекер",
  LITERARY_EDITOR: "Литературный редактор",
  STYLE_GUARDIAN: "Контроль авторского голоса",
  BOOK: "Книга",
  CHAPTER: "Глава",
  BOOK_CONTRACT_FULFILLMENT: "Выполнение контракта книги",
  CHAPTER_CONTRACT_FULFILLMENT: "Выполнение контракта главы",
  SEMANTIC_NOVELTY: "Смысловая новизна",
  IDEA_REPETITION: "Повторы идей",
  CONTRADICTION_INCONSISTENCY: "Противоречия",
  THOUGHT_DENSITY: "Плотность мысли",
  SPECIFICITY_GENERICNESS: "Конкретность",
  EVIDENCE_UNSUPPORTED_CLAIMS: "Доказательность",
  AUTHOR_VOICE: "Авторский голос",
  AI_PROSE_PATHOLOGY: "Нейросетевой мусор и шаблоны",
  OPENING_ENDING_TRANSITION: "Начала, финалы и переходы",
  CROSS_BOOK_COHERENCE: "Цельность книги",
  IDEA: "Идея",
  BOOK_DEFINITION: "Определение книги",
  RESEARCH: "Исследование",
  ARCHITECTURE: "Архитектура",
  CHAPTER_CONTRACTS: "Контракты глав",
  DRAFTING: "Написание",
  BOOK_MEMORY: "Память книги",
  EDITORIAL: "Редактура",
  BOOKBENCH: "BookBench",
  FINAL_REVIEW: "Финальная проверка",
  LITERARY_MASTER: "Литературный мастер",
  PRODUCT_DEFECT: "Дефект продукта",
  WORKFLOW_FRICTION: "Неудобство процесса",
  MISSED_ERROR: "Пропущенная ошибка",
  BOOKBENCH_FALSE_POSITIVE: "Ложное срабатывание BookBench",
  BOOKBENCH_FALSE_NEGATIVE: "Пропуск BookBench",
  MODEL_QUALITY_FAILURE: "Проблема качества модели",
  VOICE_FAILURE: "Нарушение авторского голоса",
  RESEARCH_TRACEABILITY_FAILURE: "Проблема проверяемости исследования",
  HUMAN_DECISION_REASON: "Причина человеческого решения",
  OTHER: "Другое",
  LOADING: "Загрузка",
};

export function uiLabel(value: string | null | undefined): string {
  if (!value) return "—";
  return LABELS[value] ?? value.replaceAll("_", " ");
}
