from __future__ import annotations

from .mystery_anti_cliche_validation import (
    AntiClicheRule,
    AntiClicheRulePack,
)


def _rule(
    code: str,
    level: str,
    category: str,
    title: str,
    description: str,
    *,
    exception_allowed: bool = False,
) -> AntiClicheRule:
    return AntiClicheRule(
        code=code,
        level=level,  # type: ignore[arg-type]
        category=category,
        title=title,
        description=description,
        exception_allowed=exception_allowed,
        semantic_review_required=True,
    )


BLOCKED = "BLOCKED_BY_DEFAULT"
HIGH = "HIGH_RISK_TROPE"
STYLE = "STYLE_PATHOLOGY"
SERIES = "SERIES_COLLISION"

DEFAULT_MYSTERY_ANTI_CLICHE_RULE_PACK = AntiClicheRulePack(
    pack_id="mystery-os-default",
    version=1,
    rules=(
        _rule(
            "TWIST.PROTAGONIST_KILLER",
            BLOCKED,
            "MYSTERY_TWIST",
            "Протагонист оказался убийцей",
            "Развязка делает детектива/протагониста убийцей без строго fair-play конструкции.",
            exception_allowed=True,
        ),
        _rule(
            "TWIST.SECRET_TWIN",
            BLOCKED,
            "MYSTERY_TWIST",
            "Поздний близнец или неизвестный родственник",
            "Идентичный близнец/неизвестный родственник вводится поздно, чтобы спасти невозможный сюжет.",
            exception_allowed=True,
        ),
        _rule(
            "TWIST.VICTIM_NOT_DEAD",
            BLOCKED,
            "MYSTERY_TWIST",
            "Жертва была жива",
            "Оказывается, что жертва не умерла, без сильной предварительной доказательной базы.",
            exception_allowed=True,
        ),
        _rule(
            "TWIST.EVERYONE_DID_IT",
            BLOCKED,
            "MYSTERY_TWIST",
            "Сделали все",
            "Коллективная вина используется как заимствованный престижный твист, а не как органичная причинная конструкция.",
            exception_allowed=True,
        ),
        _rule(
            "CULPRIT.UNDERDEVELOPED_SURPRISE",
            BLOCKED,
            "CULPRIT",
            "Убийца — наименее разработанный персонаж",
            "Виновным назначен малозаметный персонаж только ради неожиданности.",
            exception_allowed=True,
        ),
        _rule(
            "CULPRIT.CREEPY_LONER_DEFAULT",
            BLOCKED,
            "CULPRIT",
            "Жуткий одиночка по умолчанию",
            "Очевидно странный/нелюдимый персонаж оказывается виновным без более глубокой причинной конструкции.",
            exception_allowed=True,
        ),
        _rule(
            "TWIST.DREAM_HALLUCINATION_COMA",
            BLOCKED,
            "MYSTERY_TWIST",
            "Это был сон, галлюцинация или кома",
            "Сон/галлюцинация/кома заменяет основное объяснение событий.",
            exception_allowed=True,
        ),
        _rule(
            "MOTIVE.PSYCHIATRIC_DIAGNOSIS_SHORTCUT",
            BLOCKED,
            "CULPRIT",
            "Диагноз как универсальное объяснение",
            "Психиатрический диагноз используется как готовая причина насилия, мистики или нелогичного поведения.",
            exception_allowed=True,
        ),
        _rule(
            "DEVICE.AMNESIA_INFORMATION_HIDE",
            BLOCKED,
            "PLOT_DEVICE",
            "Амнезия для сокрытия знания POV",
            "Амнезия нужна главным образом затем, чтобы скрыть информацию, которую viewpoint-персонаж иначе знал бы.",
            exception_allowed=True,
        ),
        _rule(
            "SOLUTION.CONFESSION_REPLACES_PROOF",
            BLOCKED,
            "MYSTERY_LOGIC",
            "Признание вместо доказательства",
            "Финальное признание заменяет независимую доказательную цепочку.",
            exception_allowed=True,
        ),
        _rule(
            "CLUE.CRYPTIC_DYING_MESSAGE",
            BLOCKED,
            "CLUE",
            "Удобное зашифрованное послание умирающего",
            "Жертва оставляет неправдоподобно загадочную подсказку только потому, что жанру нужен ребус.",
            exception_allowed=True,
        ),
        _rule(
            "MECHANISM.SECRET_PASSAGE_LATE",
            BLOCKED,
            "MECHANISM",
            "Тайный ход появляется для развязки",
            "Секретный ход/комната возникает лишь тогда, когда он нужен решению.",
            exception_allowed=True,
        ),
        _rule(
            "TECH.CONVENIENT_FAILURE",
            BLOCKED,
            "REALISM",
            "Камера, телефон или сеть ломаются вовремя",
            "Камера/телефон/батарея/сеть отказывает ровно в нужный момент без причинной подготовки.",
            exception_allowed=True,
        ),
        _rule(
            "FORENSICS.LATE_DECISIVE_FACT",
            BLOCKED,
            "FAIR_PLAY",
            "Поздняя решающая экспертиза",
            "Ранее не упомянутый криминалистический факт появляется в финале и решает дело.",
            exception_allowed=True,
        ),
        _rule(
            "SOLUTION.COINCIDENCE_IDENTIFIES_CULPRIT",
            BLOCKED,
            "MYSTERY_LOGIC",
            "Совпадение называет преступника",
            "После провала расследования виновного определяет случайное совпадение.",
            exception_allowed=True,
        ),
        _rule(
            "CULPRIT.DISCOVERABLE_TROPHY_SHRINE",
            BLOCKED,
            "CULPRIT",
            "Удобный алтарь трофеев",
            "Преступник хранит фотографии/вырезки/трофеи в абсурдно легко обнаруживаемом месте без характерной причины.",
            exception_allowed=True,
        ),
        _rule(
            "CLIMAX.VILLAIN_EXPLAINS_PLAN",
            BLOCKED,
            "CLIMAX",
            "Злодей рассказывает весь план",
            "Виновный объясняет всё герою, откладывая простой побег/убийство/арест только ради экспозиции.",
            exception_allowed=True,
        ),
        _rule(
            "SUP.ENTITY_REMOVES_HUMAN_AGENCY",
            BLOCKED,
            "SUPERNATURAL",
            "Сущность заставила человека",
            "Мистика заменяет человеческий мотив и ответственность формулой «сущность заставила».",
            exception_allowed=True,
        ),
        _rule(
            "SUP.PROPHECY_ENCODES_ANSWER",
            BLOCKED,
            "SUPERNATURAL",
            "Пророчество уже содержит ответ",
            "Видение/пророчество сообщает решение в шифре, а финал только расшифровывает его.",
            exception_allowed=True,
        ),
        _rule(
            "SUP.INHERITED_OLD_MANSION",
            BLOCKED,
            "SUPERNATURAL",
            "Унаследованный старый дом как портал зла",
            "Наследство, старый дом или усадьба автоматически становятся источником мистики.",
            exception_allowed=True,
        ),
        _rule(
            "SUP.DUSTY_ARCHIVE_EXPLAINS_MYSTERY",
            BLOCKED,
            "SUPERNATURAL",
            "Архивная пыль объясняет тайну",
            "Старые письма, дневники, газетные вырезки или архив становятся главным механизмом объяснения загадки.",
            exception_allowed=True,
        ),
        _rule(
            "SUP.BOOKCASE_SECRET_ROOM",
            BLOCKED,
            "SUPERNATURAL",
            "Комната за книжным шкафом",
            "Секретная комната за шкафом используется в стандартной функции без существенного нового причинного смысла.",
            exception_allowed=True,
        ),
        _rule(
            "SUP.HAUNTED_ANTIQUE_DEFAULT",
            BLOCKED,
            "SUPERNATURAL",
            "Типовой проклятый предмет",
            "Зеркало, кукла, музыкальная шкатулка, портрет или антиквариат используются как стандартный носитель зла.",
            exception_allowed=True,
        ),
        _rule(
            "SUP.CHILD_DRAWS_MONSTER",
            BLOCKED,
            "SUPERNATURAL",
            "Ребёнок рисует монстра",
            "Ребёнок заранее рисует сущность, а взрослые игнорируют очевидное предупреждение.",
            exception_allowed=True,
        ),
        _rule(
            "SUP.GENERIC_PRESENCE_SIGNALS",
            BLOCKED,
            "SUPERNATURAL",
            "Мигание света как доказательство присутствия",
            "Свет, часы, холод и электроника служат стандартным комплектом доказательства призрака без специфической механики.",
            exception_allowed=True,
        ),
        _rule(
            "SUP.CONVENIENT_CRYPTIC_GHOST",
            BLOCKED,
            "SUPERNATURAL",
            "Призрак говорит обрывками ради задержки",
            "Сущность сообщает только удобные загадочные фрагменты, потому что полная фраза закончила бы сюжет.",
            exception_allowed=True,
        ),
        _rule(
            "SUP.LATIN_CURSE_EXPLAINS_ALL",
            BLOCKED,
            "SUPERNATURAL",
            "Латинская надпись объясняет проклятие",
            "Древняя/латинская надпись удобно раскрывает правила мистики.",
            exception_allowed=True,
        ),
        _rule(
            "SUP.GENERIC_OCCULT_SYMBOL",
            BLOCKED,
            "SUPERNATURAL",
            "Типовой оккультный знак",
            "Пентаграмма или абстрактный символ используется как быстрый маркер «тёмного ритуала».",
            exception_allowed=True,
        ),
        _rule(
            "SUP.ALL_KNOWING_KEEPER_REFUSES",
            BLOCKED,
            "SUPERNATURAL",
            "Знающий хранитель молчит без причины",
            "Старуха/хранитель знает всё, но отказывается объяснять без правдоподобной мотивации.",
            exception_allowed=True,
        ),
        _rule(
            "SUP.LOCAL_LEGEND_LITERAL",
            BLOCKED,
            "SUPERNATURAL",
            "Легенда исполняется буквально",
            "Местную легенду пересказывают как экспозицию, после чего события просто повторяют её.",
            exception_allowed=True,
        ),
        _rule(
            "SUP.CURSED_LAND_GENERIC",
            BLOCKED,
            "SUPERNATURAL",
            "Земля была проклята",
            "Древнее проклятие места используется без конкретной социальной/причинной функции.",
            exception_allowed=True,
        ),
        _rule(
            "SUP.HORROR_TIMING_NOT_RULES",
            BLOCKED,
            "SUPERNATURAL",
            "Сущность действует по таймингу хоррора",
            "Мистика атакует тогда, когда нужен испуг, а не когда выполняются заявленные правила.",
            exception_allowed=True,
        ),
        _rule(
            "SUP.UNDECLARED_RITUAL_SOLVES",
            BLOCKED,
            "SUPERNATURAL",
            "Ритуал внезапно решает проблему",
            "Экзорцизм/ритуал решает явление, чьи механики ранее не были установлены.",
            exception_allowed=True,
        ),
        _rule(
            "SUP.CHOSEN_BY_BLOODLINE",
            BLOCKED,
            "SUPERNATURAL",
            "Избранность по крови в кульминации",
            "Герой внезапно узнаёт, что обладает уникальным даром из-за происхождения.",
            exception_allowed=True,
        ),
        _rule(
            "SUP.CONVENIENT_PSYCHIC",
            BLOCKED,
            "SUPERNATURAL",
            "Удобный экстрасенс",
            "Экстрасенс извлекает ровно ту улику, которой сейчас не хватает сюжету.",
            exception_allowed=True,
        ),
        _rule(
            "SUP.REPEATED_DEAD_CALL_FIXED_ENGINE",
            BLOCKED,
            "SUPERNATURAL",
            "Звонок мёртвого как повторяемая формула",
            "Звонки/сообщения умерших становятся неизменным двигателем каждой книги без самостоятельной оригинальной системы правил и последствий.",
            exception_allowed=True,
        ),
        _rule(
            "INVESTIGATOR.RUDE_GENIUS_ALWAYS_RIGHT",
            HIGH,
            "INVESTIGATOR",
            "Гениальный хам всегда прав",
            "Блестящий сыщик груб со всеми и почти не ошибается; требуется индивидуализация и реальные ограничения.",
        ),
        _rule(
            "INVESTIGATOR.DECORATIVE_BURNOUT",
            HIGH,
            "INVESTIGATOR",
            "Алкоголь, развод и выгорание как готовая глубина",
            "Жанровая травма существует как декорация, а не как причинная часть решений.",
        ),
        _rule(
            "INVESTIGATOR.TRAGIC_DEAD_FAMILY_DEPTH",
            HIGH,
            "INVESTIGATOR",
            "Мёртвый близкий как мгновенная глубина",
            "Погибший супруг/ребёнок используется как универсальная кнопка характера.",
        ),
        _rule(
            "INVESTIGATOR.HUMAN_LIE_DETECTOR",
            HIGH,
            "INVESTIGATOR",
            "Человек-детектор лжи",
            "Герой делает достоверные выводы о лжи по микрожестам без достаточной опоры.",
        ),
        _rule(
            "INVESTIGATOR.CONVENIENT_EXPERT_FRIEND",
            HIGH,
            "INVESTIGATOR",
            "Друг-хакер/коронер решает любую задачу",
            "Вспомогательный эксперт выдаёт любую нужную информацию по требованию сюжета.",
        ),
        _rule(
            "INVESTIGATOR.OFFICIALS_STUPID",
            HIGH,
            "INVESTIGATOR",
            "Все официальные следователи глупее героя",
            "Компетентность протагониста строится на искусственной тупости окружающих.",
        ),
        _rule(
            "CULPRIT.GENERIC_CHILDHOOD_TRAUMA",
            HIGH,
            "CULPRIT",
            "Серийный убийца из-за типовой детской травмы",
            "Травма детства используется как готовый мотив без индивидуальной причинности.",
        ),
        _rule(
            "PLOT.ZODIAC_TAROT_THEME",
            HIGH,
            "PLOT_ENGINE",
            "Зодиак/таро/семь грехов как серия убийств",
            "Тематическая серия преступлений строится на знакомом коде без специфической причинной необходимости.",
        ),
        _rule(
            "PLOT.PROTAGONIST_NEXT_VICTIM",
            HIGH,
            "PLOT_ENGINE",
            "Следующая жертва — герой",
            "Угроза протагонисту используется как автоматическая эскалация третьего акта.",
        ),
        _rule(
            "PLOT.KIDNAPPED_FAMILY_ISOLATES_HERO",
            HIGH,
            "PLOT_ENGINE",
            "Похищение близкого изолирует расследователя",
            "Близкого похищают главным образом для вывода героя из нормальной процедуры.",
        ),
        _rule(
            "PLOT.SECRET_SOCIETY_EVERYTHING",
            HIGH,
            "PLOT_ENGINE",
            "Тайное общество стоит за всем",
            "Скрытая организация расширяется до универсального объяснения препятствий.",
        ),
        _rule(
            "RELATIONSHIP.HOSTILITY_TO_ROMANCE",
            HIGH,
            "RELATIONSHIP",
            "Искусственная вражда превращается в роман",
            "Начальная неприязнь существует почти исключительно как топливо для будущей романтики.",
        ),
        _rule(
            "RELATIONSHIP.MISUNDERSTANDING_JEALOUSY",
            HIGH,
            "RELATIONSHIP",
            "Ревность из легко решаемого недоразумения",
            "Взрослые персонажи избегают одной нормальной фразы ради растяжения романтического конфликта.",
        ),
        _rule(
            "STYLE.NE_X_A_Y_OVERUSE",
            STYLE,
            "PROSE",
            "Повтор конструкции «не X, а Y»",
            "Частое использование одной риторической конструкции создаёт узнаваемую модельную гладкость.",
        ),
        _rule(
            "STYLE.PSEUDO_APHORISM_ONE_LINERS",
            STYLE,
            "PROSE",
            "Псевдоафористические однострочники",
            "Однострочные абзацы систематически используются для искусственного веса.",
        ),
        _rule(
            "STYLE.ARTIFICIAL_TRIPLES",
            STYLE,
            "PROSE",
            "Искусственные тройки",
            "Регулярные тройки прилагательных, действий или откровений выдают шаблонную риторику.",
        ),
        _rule(
            "STYLE.GENERIC_SENSORY_PACKAGES",
            STYLE,
            "PROSE",
            "Повтор сенсорных наборов",
            "Одинаковые запахи, холод, тени и телесные реакции повторяются как универсальная атмосфера.",
        ),
        _rule(
            "STYLE.CHAPTER_END_TEASER_FORMULA",
            STYLE,
            "PROSE",
            "Каждая глава заканчивается тизером",
            "Повторяется одна и та же синтаксическая модель клиффхэнгера без нового состояния истории.",
        ),
        _rule(
            "STYLE.EXCESSIVE_TENSION_FRAGMENTS",
            STYLE,
            "PROSE",
            "Обрывки вместо напряжения",
            "Чрезмерные фрагменты предложений используются как механический ускоритель напряжения.",
        ),
        _rule(
            "STYLE.SHE_DID_NOT_KNOW_BAIT",
            STYLE,
            "POV",
            "«Она ещё не знала...»",
            "Всеведущий тизер вторгается в ограниченный POV только ради дешёвого предвосхищения.",
        ),
        _rule(
            "STYLE.EVERYTHING_CHANGED_CLIFFHANGER",
            STYLE,
            "PROSE",
            "«Всё изменилось / это было только начало»",
            "Абстрактная фраза заменяет конкретное изменение состояния.",
        ),
        _rule(
            "STYLE.GENERIC_BODY_REACTIONS",
            STYLE,
            "PROSE",
            "Замирает, сглатывает, сжимает кулаки",
            "Повторный набор телесных реакций подменяет индивидуальное поведение и эмоцию.",
        ),
        _rule(
            "STYLE.CAMERA_PROSE_OUTSIDE_POV",
            STYLE,
            "POV",
            "Кинематографическая камера вне сознания героя",
            "Описание ведёт себя как внешняя камера и теряет embodied viewpoint.",
        ),
        _rule(
            "STYLE.EXPLAINS_AFTER_DIALOGUE",
            STYLE,
            "DIALOGUE",
            "Объяснение после уже понятного диалога",
            "Нарратив пересказывает смысл реплик, который сцена уже показала.",
        ),
        _rule(
            "STYLE.MACHINE_SYMMETRY",
            STYLE,
            "STRUCTURE",
            "Машинная симметрия сцен",
            "Слишком одинаковые длины, ритмы и beat-паттерны делают конструкцию видимой.",
        ),
        _rule(
            "SERIES.SAME_CASE_SURFACE_RENAME",
            SERIES,
            "SERIES",
            "Тот же кейс с другими именами",
            "Сохраняется архитектура решения/механизма, меняются только профессии, имена или место.",
        ),
        _rule(
            "SERIES.SAME_RELATIONSHIP_BEAT",
            SERIES,
            "SERIES",
            "Повтор эмоционального шага пары",
            "Между постоянными героями снова проигрывается уже использованный конфликт/примирение.",
        ),
        _rule(
            "SERIES.SAME_FINAL_STAGING",
            SERIES,
            "SERIES",
            "Повтор финальной постановки",
            "Финальная конфронтация повторяет прошлую книгу с заменёнными декорациями.",
        ),
    ),
)
